name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Select Node Version
        uses: svierk/get-node-version@main
      - name: Install Dependencies
        run: npm ci
      - name: Install SF CLI
        uses: svierk/sfdx-cli-setup@main
      - name: Salesforce Org Login
        uses: svierk/sfdx-login@main
        with:
          client-id: ${{ secrets.SFDX_CONSUMER_KEY }}
          jwt-secret-key: ${{ secrets.SFDX_JWT_SECRET_KEY }}
          username: ${{ secrets.SFDX_USERNAME }}
      - name: Deploy Metadata
        run: sf project deploy start
      # - name: Deploy Data
      #   run: 

