name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Select Node Version
        uses: svierk/get-node-version@main
      - name: Install Dependencies
        run: npm ci
      - name: Install SF CLI
        uses: svierk/sfdx-cli-setup@main
      - name: Salesforce Org Login
        uses: svierk/sfdx-login@main
        with:
          client-id: ${{ secrets.SFDX_CONSUMER_KEY }}
          jwt-secret-key: ${{ secrets.SFDX_JWT_SECRET_KEY }}
          username: ${{ secrets.SFDX_USERNAME }}
          alias: cpq-org
      - name: CPQ Metadata Deployment
        run: sf project deploy start
      - name: CPQ Data import
        run: |
          sf data upsert bulk --sobject SBQQ__ProductFeature__c --file ./data/SBQQ__ProductFeature__c.csv --external-id Id --wait 5 --target-org cpq-org